name = "Zoified"
license = "MIT"
licenselink = "https://github.com/zoe-translates/hugo-theme-zoified/blob/main/LICENSE"
description = "Ed theme for minimal editions, based on Alex Gil theme, with modifications specially crafted for zoe-translat.es"

# The home page of the theme, where the source can be found.
homepage = "https://github.com/zoe-translates/hugo-theme-zoified/"

# If you have a running demo of the theme.
demosite = ""

tags = [
  "blog",
  "clean",
  "customizable",
  "ed",
  "light",
  "minimal",
  "minimalist",
  "multilingual",
  "responsive",
  "search",
  "simple"
]

# The theme's features:
features = [
  "blog",
  "clean",
  "contact form",
  "favicon",
  "jsonfeed",
  "minimal",
  "minimalist",
  "mobile",
  "multilingual",
  "opengraph",
  "posts",
  "responsive",
  "rss",
  "search",
  "shortcodes",
  "simple"
]

min_version = "0.95.0"

# If the theme has a single author.
[author]
  name = "Zoë C."
  homepage = "https://zoe-translat.es/"

[original]
  name = "Serghei Iakovlev"
  homepage = "https://serghei.blog/"
